# Generated by Django 5.2.11 on 2026-02-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('billing', 'Billing'), ('account', 'Account'), ('bug', 'Bug'), ('feature', 'Feature'), ('other', 'Other')], db_index=True, default='other', help_text='Categoria funzionale del ticket (es. billing, bug, question). Predetta anche dal modello ML.', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', help_text='Stato del ticket nel workflow (open, in_progress, resolved, ...)', max_length=20),
        ),
    ]
